require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkgroupsController do

  # This should return the minimal set of attributes required to create a valid
  # Workgroup. As you add validations to Workgroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkgroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all workgroups as @workgroups" do
      workgroup = Workgroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:workgroups).should eq([workgroup])
    end
  end

  describe "GET show" do
    it "assigns the requested workgroup as @workgroup" do
      workgroup = Workgroup.create! valid_attributes
      get :show, {:id => workgroup.to_param}, valid_session
      assigns(:workgroup).should eq(workgroup)
    end
  end

  describe "GET new" do
    it "assigns a new workgroup as @workgroup" do
      get :new, {}, valid_session
      assigns(:workgroup).should be_a_new(Workgroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested workgroup as @workgroup" do
      workgroup = Workgroup.create! valid_attributes
      get :edit, {:id => workgroup.to_param}, valid_session
      assigns(:workgroup).should eq(workgroup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Workgroup" do
        expect {
          post :create, {:workgroup => valid_attributes}, valid_session
        }.to change(Workgroup, :count).by(1)
      end

      it "assigns a newly created workgroup as @workgroup" do
        post :create, {:workgroup => valid_attributes}, valid_session
        assigns(:workgroup).should be_a(Workgroup)
        assigns(:workgroup).should be_persisted
      end

      it "redirects to the created workgroup" do
        post :create, {:workgroup => valid_attributes}, valid_session
        response.should redirect_to(Workgroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workgroup as @workgroup" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workgroup.any_instance.stub(:save).and_return(false)
        post :create, {:workgroup => {}}, valid_session
        assigns(:workgroup).should be_a_new(Workgroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workgroup.any_instance.stub(:save).and_return(false)
        post :create, {:workgroup => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workgroup" do
        workgroup = Workgroup.create! valid_attributes
        # Assuming there are no other workgroups in the database, this
        # specifies that the Workgroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Workgroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => workgroup.to_param, :workgroup => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested workgroup as @workgroup" do
        workgroup = Workgroup.create! valid_attributes
        put :update, {:id => workgroup.to_param, :workgroup => valid_attributes}, valid_session
        assigns(:workgroup).should eq(workgroup)
      end

      it "redirects to the workgroup" do
        workgroup = Workgroup.create! valid_attributes
        put :update, {:id => workgroup.to_param, :workgroup => valid_attributes}, valid_session
        response.should redirect_to(workgroup)
      end
    end

    describe "with invalid params" do
      it "assigns the workgroup as @workgroup" do
        workgroup = Workgroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workgroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => workgroup.to_param, :workgroup => {}}, valid_session
        assigns(:workgroup).should eq(workgroup)
      end

      it "re-renders the 'edit' template" do
        workgroup = Workgroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workgroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => workgroup.to_param, :workgroup => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workgroup" do
      workgroup = Workgroup.create! valid_attributes
      expect {
        delete :destroy, {:id => workgroup.to_param}, valid_session
      }.to change(Workgroup, :count).by(-1)
    end

    it "redirects to the workgroups list" do
      workgroup = Workgroup.create! valid_attributes
      delete :destroy, {:id => workgroup.to_param}, valid_session
      response.should redirect_to(workgroups_url)
    end
  end

end
